//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by winprom.rc
//
#define ID_VIEW_MAP_CONTOURS            90
#define IDC_FILTER                      92
#define IDD_ABOUTBOX                    100
#define IDC_MAJOR                       101
#define IDC_NAME                        102
#define ID_VIEW_MAP_SET                 102
#define IDC_STANDARD                    102
#define IDC_AF_DEG                      102
#define IDC_MIN_PROM                    103
#define IDC_ELEV_MIDPT                  103
#define IDC_MINOR                       103
#define ID_VIEW_PROFILE_ZOOM_TALLER     103
#define IDD_ADDRESS                     103
#define IDC_AF_DM                       103
#define IDC_LOCATION                    104
#define IDC_NAME_IS                     104
#define IDC_ELEV_RANGE                  104
#define IDC_AF_DMS                      104
#define ID_LIST_PEAKS                   105
#define IDC_NAME_CONTAINS               105
#define IDC_ELEV_EXTREMES               105
#define IDC_AF_RAD                      105
#define IDC_NAME_ISNOT                  106
#define ID_OP_PURGE_PEAKS               106
#define IDC_AF_GRAD                     106
#define IDC_NAME_CONTAINSNOT            107
#define IDC_NAME_NONE                   107
#define ID_OP_COMPRESS_PEAKS            107
#define IDC_UNIT_UTM                    107
#define IDC_NEWS                        108
#define IDC_HIGH                        108
#define IDC_NAME_TEXT                   108
#define IDC_NAME_ALT_ELEV               108
#define ID_OP_COMPRESS_ALL              109
#define IDC_LOW                         110
#define IDC_NAME_ALT_LOC                110
#define IDC_EDITED                      111
#define ID_VIEW_PROFILE_ZOOM_SHORTER    111
#define ID_VIEW_PROFILE_ZOOM_WIDER      112
#define IDC_NAME_SEPARATE               112
#define ID_VIEW_PROFILE_ZOOM_NARROWER   113
#define IDC_VIEW                        114
#define IDC_DELETE                      115
#define IDC_EDGE_EFFECT                 116
#define IDC_OFFMAP                      116
#define ID_VIEW_PROFILE_PARAMS          116
#define ID_LIST_BASINSADLS              118
#define ID_OP_PURGE_BASINSADLS          119
#define ID_OP_COMPRESS_RUNOFFS          121
#define ID_OP_COMPRESS_BASINSADLS       122
#define ID_LIST_SADDLES                 125
#define ID_OPEN_ELEV_MAP                127
#define IDR_MAINFRAME                   128
#define IDR_GRAPHTYPE                   129
#define ID_OPEN_DLPR_MAP                130
#define ID_OPEN_DLPR_TREE               131
#define IDD_MAP_INFO                    132
#define ID_MERGE_ELEV_MAP               133
#define IDD_LOCATION_FMT                133
#define ID_MERGE_DLPR_MAP               134
#define IDD_TREE_INFO                   134
#define ID_MERGE_DLPR_TREE              135
#define IDD_FEATURE                     135
#define IDR_FILE_ELEV_MAP               136
#define ID_SAVE_ELEV_MAP                137
#define ID_SAVE_DLPR_MAP                138
#define IDR_FILE_DLPR_MAP               138
#define ID_SAVE_DLPR_TREE               139
#define IDR_FILE_DLPR_TREE              139
#define ID_SAVE_ALL                     140
#define IDD_FEATURE_FMT                 140
#define ID_SAVEAS_ELEV_MAP              141
#define IDD_ANALYZE_CTL                 141
#define ID_SAVEAS_DLPR_MAP              142
#define IDI_SADDLE                      142
#define ID_SAVEAS_DLPR_TREE             143
#define IDI_SBRO                        143
#define IDI_BASINSADL                   144
#define ID_CLOSE_ELEV_MAP               145
#define ID_CLOSE_DLPR_MAP               146
#define ID_CLOSE_DLPR_TREE              147
#define ID_CLOSE_ALL                    148
#define IDI_PEAK                        154
#define ID_VIEW_LABEL_PEAK              155
#define IDI_NOEDIT                      156
#define ID_VIEW_LABEL_BASINSADL         156
#define ID_VIEW_LABEL_RUNOFF            157
#define ID_VIEW_LABEL_SADDLE            158
#define ID_VIEW_ZOOM_WAYIN              161
#define IDD_LIST_SADDLE                 161
#define IDD_FEATURE_SUMMARY             162
#define ID_VIEW_ZOOM_IN                 162
#define IDD_RUNOFF_LIST                 163
#define ID_VIEW_ZOOM_OUT                163
#define ID_VIEW_ZOOM_WAYOUT             164
#define IDD_PROMSADL                    164
#define IDD_ALL_INFO                    165
#define IDD_ELEV_CONFLICT               166
#define IDD_PURGE                       167
#define ID_OP_ANALYZE                   169
#define ID_OP_SPLICE                    170
#define IDD_CONTOUR                     171
#define ID_OP_RUN                       171
#define IDD_SET_LOCATION                172
#define ID_OP_ROTATE                    176
#define IDR_MENU_POPUP                  177
#define IDD_RUNOFF_NBR                  178
#define ID_VIEW_FEATURES_PEAKS          179
#define IDD_ELEV_RECT                   179
#define ID_VIEW_FEATURES_SADDLES        180
#define IDD_IDENTIFY_FEATURE            180
#define ID_VIEW_FEATURES_RUNOFFS        181
#define IDD_PROFILE_PARAM               181
#define ID_VIEW_FEATURES_BASINSADL      182
#define ID_OP_RESORT_NBRS               184
#define IDD_TREE_FILTER                 184
#define ID_OP_MAINT_ALL                 185
#define IDD_TREE_PASTE                  187
#define IDI_EDGE                        189
#define IDI_NOEDIT_EDGE                 190
#define IDD_PROFILE_SET                 191
#define IDD_SCRIPT_CTL                  192
#define IDD_GP_FILTER                   193
#define IDI_PROMSADL_LIST               194
#define IDI_CYCLE                       195
#define IDD_ERROR_FILTER                196
#define ID_INFO_ELEV_MAP                197
#define IDD_CYCLE                       197
#define ID_INFO_DLPR_MAP                198
#define IDD_TRANSFORM                   198
#define ID_INFO_DLPR_TREE               199
#define IDI_MIXED                       199
#define ID_INFO_ALL                     200
#define IDD_SWI                         200
#define IDR_FEATURE_LIST                201
#define IDR_LPR_TREE                    202
#define IDR_DATABASE                    203
#define IDD_IMPARAM                     204
#define IDR_ELEV                        204
#define IDD_IMPOUT                      206
#define IDI_BASIN                       207
#define IDI_RUNOFF                      208
#define IDD_TREE_SELECT                 209
#define IDD_DATA                        210
#define IDD_FIELDS                      211
#define IDD_DATA_INFO                   213
#define IDR_FILE_DATABASE               218
#define IDR_DATA_LIST                   219
#define IDD_PRINT_MAP                   221
#define IDD_DATA_FILTER                 222
#define IDI_BASINSADL_LIST              223
#define IDB_TEXT                        227
#define IDB_HTML                        228
#define IDB_CSV                         229
#define IDD_TRANSFER                    230
#define IDD_DATA_ALIGN                  232
#define IDD_RELIEF                      234
#define IDD_ERROR_PARAMS                235
#define IDR_BROWSER                     237
#define IDI_MIXED_DRAIN                 238
#define IDR_SCRIPT                      239
#define IDR_DOMAP                       240
#define IDD_BROWSE_FMT                  242
#define IDD_CROP                        247
#define IDD_DEFINE_FLAT                 248
#define IDD_TRANSFORM_TREE              250
#define IDB_GRAPH_DRAIN                 254
#define IDB_GRAPHTYPE                   255
#define IDD_RQF_INFO                    257
#define IDD_SHORE                       258
#define IDD_STAT_OPTIONS                259
#define IDD_DATA_IMPORT                 261
#define IDB_SPLASH                      263
#define IDD_NOISE_SUM                   264
#define IDD_ELEV_COLOR                  266
#define IDD_TRANSPAL                    267
#define IDD_ASSOC                       270
#define IDD_RIDGE_VIEW                  273
#define IDD_GRID_VIEW                   275
#define IDD_PURGE_DOMAIN                280
#define IDD_PARENTS                     282
#define IDI_OFFMAP                      283
#define IDD_SCALE                       287
#define IDD_FH_PARAM                    288
#define IDD_FH_OUT                      290
#define IDD_FEATURE_FILTER              519
#define IDD_DATA_SUMMARY                520
#define IDD_DATA_LOC_FILTER             522
#define IDD_ERROR_ANALYSIS              524
#define IDD_ERROR_ANALYSIS1             525
#define IDD_ERROR_ANAL                  526
#define IDD_PURGE_NOISE                 528
#define IDD_ELEV_MAP_INFO               529
#define IDD_DOMAP_INFO                  530
#define IDD_DOMAIN_VIEW                 531
#define IDD_LIST                        532
#define IDD_FEATURE_VIEW                533
#define IDD_PROM_CUTOFF                 534
#define IDD_CUTOFF_ONLY                 535
#define IDD_FEATURE_TYPE_FILTER         536
#define ID_GP_NEW_RUNOFF                770
#define IDC_ALLOC_W                     1002
#define IDC_ELEV_LOW                    1003
#define IDC_ALLOC_N                     1004
#define IDC_ALLOC_E                     1005
#define IDC_ALLOC_S                     1006
#define IDC_ALLOC_GP                    1007
#define IDC_ALLOC_AREA                  1008
#define IDC_DEFINED_W                   1009
#define IDC_DEFINED_N                   1010
#define IDC_DEFINED_E                   1011
#define IDC_DEFINED_S                   1012
#define IDC_DEFINED_GP                  1013
#define IDC_DEFINED_AREA                1014
#define IDC_ELEV_HIGH                   1015
#define IDC_FILE                        1016
#define IDC_PEAK_LOW                    1022
#define IDC_PEAK_HIGH                   1023
#define IDC_PEAK_COUNT                  1024
#define IDC_SADDLE_LOW                  1025
#define ID_LOCATION                     1025
#define IDC_SADDLE_HIGH                 1026
#define IDC_SADDLE_COUNT                1027
#define IDC_RUNOFF_LOW                  1028
#define IDC_RUNOFF_HIGH                 1029
#define IDC_RUNOFF_COUNT                1030
#define IDC_BASINSADL_LOW               1031
#define IDC_PRECISE                     1031
#define IDC_BASINSADL_HIGH              1032
#define IDC_SHOW_LOC                    1032
#define IDC_BASINSADL_COUNT             1033
#define IDC_SHOW_ELEV                   1033
#define IDC_CASE                        1034
#define IDC_PEAK_STORE                  1034
#define IDC_EDGE                        1035
#define IDC_RUNOFF_STORE                1036
#define IDC_COUNT                       1037
#define IDC_BASINSADL_STORE             1037
#define IDC_AREA_N                      1038
#define IDC_AREA_W                      1039
#define IDC_AREA_E                      1040
#define IDSUSPEND                       1040
#define IDC_AREA_S                      1041
#define IDC_IQ_1                        1042
#define IDC_IQ_2                        1043
#define IDC_IQ_3                        1044
#define IDC_CORNERS                     1045
#define IDC_INTERIOR                    1047
#define IDC_FORMAT                      1049
#define IDC_PROMINENCE                  1051
#define IDC_SADDLES                     1052
#define IDC_RUNOFFS                     1053
#define IDC_WORKSPACE                   1055
#define IDC_USE_WORKSPACE               1057
#define IDC_USE_FILE                    1059
#define IDC_USE_HIGH                    1060
#define IDC_USE_LOW                     1061
#define IDC_ABORT                       1062
#define IDC_WARN                        1063
#define IDC_CONTINUE                    1064
#define IDC_USE_MIDPT                   1065
#define IDC_PROM                        1067
#define IDC_LIMIT_N                     1071
#define IDC_LIMIT_W                     1072
#define IDC_LIMIT_E                     1073
#define IDC_LIMIT_S                     1074
#define IDC_AUTOZOOM                    1075
#define IDC_GRID_ONTOP                  1076
#define IDC_CONTOUR_ONTOP               1077
#define IDC_LATITUDE                    1078
#define IDC_LONGITUDE                   1079
#define IDC_DATUM                       1080
#define IDC_NONEDGE                     1081
#define IDC_RN_SAME_GP                  1082
#define IDC_RN_NBR_GP                   1083
#define IDC_RADIUS                      1084
#define IDC_RADIUS_TEXT                 1085
#define IDC_QUAD_LAT                    1091
#define IDC_QUAD_LON                    1092
#define IDC_STEP_LAT                    1093
#define IDC_CENTER_TARGET               1093
#define IDC_STEP_LON                    1094
#define IDC_SELECT_TARGET               1094
#define IDC_RUNOFF_MIDPT                1100
#define IDC_SCALE_LINEAR                1101
#define IDC_SCALE_LOG                   1102
#define IDC_SCALE_INVERSE               1103
#define IDC_LRO_HIGHEST                 1110
#define IDC_LRO_ALL                     1111
#define IDC_SC_SADDLE                   1112
#define IDC_SC_PEAK                     1113
#define IDC_LRO_NONE                    1120
#define IDC_SHOW_NEXT                   1121
#define IDC_PASTE                       1123
#define IDC_SKIP                        1124
#define IDC_CENTER                      1126
#define IDC_CUSTOM                      1127
#define IDC_RESET                       1128
#define IDC_ELEVATION                   1129
#define IDC_COMMAND                     1131
#define IDC_DLPR_ALL                    1132
#define IDC_DLPR_ANCESTORS              1133
#define IDC_DLPR_DESCENDANTS            1134
#define IDC_SADDLE_FILTER               1138
#define IDC_RUNOFF_FILTER               1139
#define IDC_PP_ENABLE                   1140
#define IDC_PP_HP_MIN                   1141
#define IDC_PP_FILTER                   1142
#define IDC_PP_SORT                     1143
#define IDC_PP_HP_MAX                   1144
#define IDC_PP_CHILD_BEST               1145
#define IDC_PP_CHILD_WORST              1146
#define IDC_AMBIG_SADL                  1150
#define IDC_MIN_ERROR                   1151
#define IDC_UNEDIT                      1152
#define IDC_CWR_NONOFFEND               1157
#define IDC_MULT                        1158
#define IDC_ADD                         1159
#define IDC_MODIFY                      1161
#define IDC_ONE                         1164
#define IDC_BOTH                        1165
#define IDC_FLAT                        1166
#define IDC_NONDEF                      1167
#define IDC_BASIN                       1168
#define IDC_DATA                        1170
#define IDC_SEARCH_PROG                 1172
#define IDC_WALKUP_PROG                 1173
#define IDC_SEARCH_PC                   1174
#define IDC_WALKUP_COUNT                1176
#define IDC_CONV_FAC                    1187
#define IDC_DISTINT                     1188
#define IDC_INTVAL                      1189
#define IDC_SPVAL                       1190
#define IDC_SPLOC                       1191
#define IDC_SPDIR                       1192
#define IDC_SPDIST                      1193
#define IDC_INTDIST                     1194
#define IDC_TYPE                        1196
#define IDC_TOGGLE_SP                   1198
#define IDC_NEAREDGE                    1199
#define IDC_CENTER_SP                   1200
#define IDC_TOGGLE                      1202
#define IDC_PK_XING                     1203
#define IDC_SADL_XING                   1204
#define IDC_PK_SELECT                   1205
#define IDC_SADL_SELECT                 1206
#define IDC_REL_ANY                     1207
#define IDC_REL_DESC                    1208
#define IDC_REL_ANC                     1209
#define IDC_ACT_SET                     1211
#define IDC_ACT_CLEAR                   1212
#define IDC_ACT_INVERT                  1213
#define IDC_FIELDS                      1214
#define IDC_FIELD_LIST                  1215
#define IDC_REMOVE                      1217
#define IDC_FLD_NAME                    1218
#define IDC_RENAME                      1219
#define IDC_NFT_INTEGER                 1221
#define IDC_NFT_REAL                    1222
#define IDC_NFT_STRING                  1223
#define IDC_RECORDS                     1225
#define IDC_ELEV_MAP                    1232
#define IDC_DOMAP                       1233
#define IDC_DIV_TREE                    1234
#define IDC_LAST_PRINT                  1237
#define IDC_PRINT_SETUP                 1238
#define IDC_PAGES                       1239
#define IDC_PRINT_N                     1240
#define IDC_PRINT_W                     1241
#define IDC_PRINT_E                     1242
#define IDC_PRINT_S                     1243
#define IDC_WINDOW                      1245
#define IDC_ACCEPT_NODATA               1247
#define IDC_UP                          1248
#define IDC_DOWN                        1249
#define IDC_RESET_TEXT                  1250
#define IDC_RESET_HTML                  1251
#define IDC_RESET_CSV                   1252
#define IDC_LIST_FILTER                 1254
#define IDC_SEPARAM                     1257
#define IDC_BIAS                        1260
#define IDC_RAW_ERR                     1264
#define IDC_FEATR_TYPE                  1269
#define IDC_NUM_FEATR                   1283
#define IDC_ORPHAN                      1294
#define IDC_INTENSITY                   1298
#define IDC_DIRECTION                   1299
#define IDC_SIGMA_OUT                   1301
#define IDC_SIGMA_IN                    1302
#define IDC_ENABLE_FIXED                1305
#define IDC_BETA                        1311
#define IDC_BIAS_STD                    1312
#define IDC_ORTHO_STD                   1313
#define IDC_DIAG_COEFF                  1314
#define IDC_LAMBDA                      1315
#define IDC_GAMMA                       1316
#define IDC_BROWSE                      1317
#define IDC_DIAG_STD                    1317
#define IDC_PROVIDER                    1318
#define IDC_ORTHO2_COEFF                1318
#define IDC_ORTHO2_STD                  1319
#define IDC_OPTION                      1319
#define IDC_SCALE                       1320
#define IDC_KNIGHT_COEFF                1320
#define IDC_MAPSIZE                     1321
#define IDC_KNIGHT_STD                  1321
#define IDC_DIAG_SLOPE                  1322
#define IDC_ORTHO2_SLOPE                1323
#define IDC_RELOAD                      1324
#define IDC_KNIGHT_SLOPE                1324
#define IDC_QUAD_COORD1                 1326
#define IDC_QUAD_COORD2                 1327
#define IDC_STEP_COORD1                 1328
#define IDC_STEP_COORD2                 1329
#define IDC_RQF_GP                      1335
#define IDC_RQF_STAT                    1336
#define IDC_ELEV_DATA                   1345
#define IDC_UPE                         1352
#define IDC_OFFMAP_SADDLES              1354
#define IDC_BASNSADL                    1356
#define IDC_ADDRESS                     1359
#define IDC_GO                          1360
#define IDC_SEARCH                      1363
#define IDC_FOUND                       1364
#define IDC_PEAKS                       1365
#define IDC_BASIN_SADLS                 1366
#define IDC_MEASURE_ERROR               1369
#define IDC_REVERT                      1371
#define IDC_BS_XING                     1375
#define IDC_NBR00                       1376
#define IDC_NBR01                       1377
#define IDC_NBR02                       1378
#define IDC_NBR10                       1379
#define IDC_NBR11                       1380
#define IDC_NBR12                       1381
#define IDC_NBR20                       1382
#define IDC_NBR21                       1383
#define IDC_NBR22                       1384
#define IDC_EIGEN1                      1385
#define IDC_EIGEN2                      1386
#define IDC_STATX                       1389
#define IDC_STATY                       1390
#define IDC_ELEV_CTR                    1391
#define IDC_ELEV_STAT                   1392
#define IDC_LAPLAC                      1393
#define IDC_CONVLUTN                    1394
#define IDC_STAT_MODEL                  1399
#define IDC_RESID_ERR                   1400
#define IDC_FIXED_ERROR                 1401
#define IDC_MORE_PARAMS                 1402
#define IDC_STRICT                      1410
#define IDC_MAHAL                       1411
#define IDC_AVG_LAPLCN                  1412
#define IDC_SADL_ELEV                   1418
#define IDC_MARK_EDIT                   1419
#define IDC_SET_EDIT                    1420
#define IDC_EXTREME_LABEL               1421
#define IDC_BASIN_ELEV                  1422
#define IDC_PEAK                        1424
#define IDC_SADDLE                      1426
#define IDC_AXIS                        1428
#define IDC_SYMMETRY                    1429
#define IDC_NEIGHBORS                   1430
#define IDC_ISOLATIN                    1431
#define IDC_MIN_NBR                     1432
#define IDC_ORTHO_COEFF                 1435
#define IDC_ORTHO_SLOPE                 1436
#define IDC_OPTIONS                     1437
#define IDC_NAME_FLD                    1438
#define IDC_ELEV_FLD                    1439
#define IDC_EDIT                        1441
#define IDC_NOISE                       1450
#define IDC_LABEL                       1451
#define IDC_RESID_ASYM1                 1452
#define IDC_RESID_ASYM2                 1453
#define IDC_HESS_NC                     1453
#define IDC_RESID_SYM                   1454
#define IDC_HESS1                       1455
#define IDC_RESID_NC                    1455
#define IDC_HESS2                       1456
#define IDC_BIG_NOISE_PROM              1457
#define IDC_BIG_NOISE                   1458
#define IDC_LATIN1                      1458
#define IDC_SADLS                       1461
#define IDC_BASNSADLS                   1463
#define IDC_NDOM                        1465
#define IDC_NDOM_0PEAK                  1466
#define IDC_COLOR_INTV                  1466
#define IDC_NDOM_PEAKS                  1467
#define IDC_NDOM_1PEAK                  1468
#define IDC_COLOR_ENABLE                1469
#define IDC_ELEV                        1470
#define IDC_COLOR                       1471
#define IDC_VOID_COLOR                  1472
#define IDC_COLOR_BOX                   1473
#define IDC_BOX_VOID                    1474
#define IDC_TRANSFORM                   1477
#define IDC_INTERP                      1478
#define IDC_LOW_NEW                     1480
#define IDC_LOW_OLD                     1481
#define IDC_HIGH_OLD                    1482
#define IDC_HIGH_NEW                    1483
#define IDC_FLAT_SEP                    1483
#define IDC_BIND_TYPE                   1484
#define IDC_NDOM_AREA                   1486
#define IDC_STAT                        1487
#define IDC_REF_MIDPT                   1488
#define IDC_REF_EXTREME                 1489
#define IDC_DOMAIN                      1525
#define IDC_WALKUP                      1526
#define IDC_SS_PROM                     1529
#define IDC_SS_BASIN                    1530
#define IDC_SS_ALL                      1531
#define IDC_NONORPH                     1532
#define IDC_OMP                         1535
#define IDC_PSR                         1537
#define IDC_PRS                         1538
#define IDC_SPR                         1539
#define IDC_SRP                         1540
#define IDC_RPS                         1541
#define IDC_RSP                         1542
#define IDC_ASSOC                       1543
#define IDC_MULT_REC_PEAK               1544
#define IDC_MULT_REC_SADL               1545
#define IDC_DISTANCE                    1546
#define IDC_RUNOFF                      1553
#define IDC_BASIN_SADL                  1554
#define IDC_CONTOUR_COLOR               1560
#define IDC_BOX_CONTOUR                 1561
#define IDC_DOMAIN_COLOR                1562
#define IDC_BOX_DOMAIN                  1563
#define IDC_ENABLE                      1564
#define IDC_GV_NONE                     1566
#define IDC_GV_POINTS                   1567
#define IDC_NOTE                        1570
#define IDC_ROTATION                    1575
#define IDC_RIDGE                       1577
#define IDC_CELL                        1578
#define IDC_ELEV_CAP                    1586
#define IDC_EDGE_SADL                   1593
#define IDC_BSNSDLS                     1605
#define IDC_BEGINS                      1606
#define IDC_ENDS                        1607
#define IDC_PT_HEIGHT                   1612
#define IDC_PT_ISLAND                   1614
#define IDC_PS_FILTER                   1616
#define IDC_EXCISE                      1618
#define IDC_ELEV_PROM                   1619
#define IDC_GV_ELEV                     1630
#define IDC_AF_UTM                      1631
#define IDC_PT_PROM                     1632
#define IDC_UNIT_DEGREES                1633
#define IDC_UNIT_RADIANS                1634
#define IDC_UNIT_GRADS                  1635
#define IDC_RN_RADIUS                   1636
#define IDC_SC_PROM                     1637
#define IDC_PATH                        1639
#define IDC_SADL_STATUS                 1646
#define IDC_SS_LABEL                    1647
#define IDC_BS_STATUS                   1647
#define IDC_PS_STATUS                   1649
#define IDC_PROM_LABEL                  1650
#define IDC_IQ_0                        1651
#define IDC_BSPT_STANDARD               1652
#define IDC_BSPT_ASSOC                  1653
#define IDC_CPDM                        1654
#define IDC_INVSQ                       1658
#define IDC_MORSE_SMALE                 1665
#define IDC_LINE                        1666
#define IDC_ISLAND                      1668
#define IDC_RADIO3                      1671
#define IDC_EQUAL_ANGLE                 1672
#define IDC_TOPO_LINE                   1674
#define IDC_TOPO_CELL                   1675
#define IDC_TOPO_ISLAND                 1676
#define IDC_PEAK_FILTER                 1677
#define IDC_SADL_FILTER                 1678
#define IDC_NFT_LOCATION                1679
#define IDC_REF_ELEV                    1681
#define IDC_FVH                         1682
#define IDC_MFH_VIEW                    1684
#define IDC_MFH_AZIM                    1689
#define IDC_MARK_ALL                    1691
#define IDC_MAX                         1692
#define IDC_ROLL_DOWN                   1693
#define IDC_ROLL_UP                     1694
#define IDC_TOP                         1695
#define IDC_ROLL_BOTTOM                 1696
#define IDC_ROLL_CENTER                 1697
#define IDC_RAD_VERT                    1698
#define IDC_FH                          1699
#define IDC_RANGE                       1700
#define ID_LIST_RUNOFFS                 32773
#define ID_VIEW_TB_ELEV_MAP             32783
#define ID_VIEW_TB_DLPR_MAP             32784
#define ID_VIEW_TB_DLPR_TREE            32785
#define ID_VIEW_TB_ALL                  32786
#define ID_VIEW_TB_NONE                 32787
#define ID_FILE_TEXT                    32792
#define ID_FILE_HTML                    32793
#define ID_VIEW_LISTX                   32798
#define ID_VIEW_REPORT                  32799
#define ID_EDIT_FEATURE                 32800
#define ID_FEATURE_EDIT                 32803
#define ID_VIEW_LARGE                   32806
#define ID_VIEW_SMALL                   32807
#define ID_VIEW_ALIGN                   32809
#define ID_VIEW_ARRANGE                 32810
#define ID_EDIT_DELETE                  32829
#define ID_EDIT_SELECT_INVERT           32838
#define ID_LIST_FORMAT                  32840
#define ID_LIST_RELIST                  32841
#define ID_LIST_SUMMARY                 32842
#define ID_EDIT_UNLIST                  32843
#define ID_EDIT_CENTER                  32844
#define ID_LIST_GENERIC                 32847
#define ID_EDIT_SELECT_FILTER_PRECISE   32848
#define ID_EDIT_SELECT_FILTER_SET       32849
#define ID_EDIT_SELECT_FILTER_CLEAR     32850
#define ID_LIST_PROMSADL                32853
#define ID_LIST_SADL                    32860
#define ID_EDIT_SPLICE                  32863
#define ID_EDIT_SELECT_OVERLAPS         32865
#define ID_EDIT_ROTATE                  32866
#define ID_VIEW_RIDGE_RUNOFF            32867
#define ID_VIEW_RIDGE_BASINSADL         32868
#define ID_VIEW_MAP_DLPRTREE            32877
#define ID_VIEW_COLORS_BG               32886
#define ID_WINDOW_MAP                   32893
#define ID_WINDOW_PROFILE               32894
#define ID_VIEW_FEATURES_ALL            32901
#define ID_VIEW_FEATURES_NONE           32902
#define ID_VIEW_LABEL_ALL               32903
#define ID_VIEW_RIDGE_ALL               32909
#define ID_VIEW_RIDGE_NONE              32910
#define ID_EDIT_UNVIEW                  32914
#define ID_OP_LPRMAP                    32918
#define ID_OP_DIAG_ERRORS               32924
#define ID_OP_DIAG_DUPS                 32926
#define ID_FEATURE_CENTER               32931
#define ID_FEATURE_UNVIEW               32932
#define ID_FEATURE_DELETE               32935
#define ID_FEATURE_LIST_SADDLES         32936
#define ID_FEATURE_LIST_NBRS            32937
#define ID_BASINSADL_ROTATE             32941
#define ID_RUNOFF_SPLICE                32942
#define ID_LIST_NBRS                    32952
#define ID_LIST_CYCLE                   32953
#define ID_VIEW_MAP_MARK_SET            32954
#define ID_VIEW_MAP_MARK_CLEAR          32955
#define ID_VIEW_MAP_MARK_PRECISE        32956
#define ID_VIEW_MAP_MARK_CLEAR_ALL      32957
#define ID_GP_MARKAREA                  32960
#define ID_GP_DLPR_PEAK                 32965
#define ID_VIEW_MAP_MARK_VIEW           32967
#define ID_IDENTIFY_SADDLE              32974
#define ID_VIEW_COLORS_LABELS           32975
#define ID_VIEW_IDENTIFY                32976
#define ID_VIEW_COLORS_MARK             32977
#define ID_GP_CENTER                    32978
#define ID_VIEW_PROFILE_SET             32985
#define ID_LIST_TREE                    32990
#define ID_FEATURE_LIST_TREE            32992
#define ID_VIEW_RIDGE_PEAK              32995
#define ID_VIEW_RIDGE_SADDLE            32996
#define ID_EDIT_SEARCH                  33001
#define ID_VIEW_HRULER                  33005
#define ID_VIEW_VRULER                  33007
#define ID_EDIT_COPY_ELEV_MAP           33008
#define ID_EDIT_COPY_DLPR_MAP           33009
#define ID_EDIT_COPY_DLPR_TREE          33010
#define ID_EDIT_PASTE_ELEV_MAP          33011
#define ID_EDIT_PASTE_DLPR_MAP          33012
#define ID_EDIT_PASTE_DLPR_TREE         33013
#define ID_EDIT_PASTE_ALL               33014
#define ID_EDIT_COPY_ALL                33015
#define ID_FEATURE_UNLIST               33020
#define ID_OP_FLAT_UNDEFINE             33022
#define ID_OP_FLAT_DEFINE               33023
#define ID_LIST_WALK                    33024
#define ID_VIEW_SCROLL_CENTER           33025
#define ID_OP_PURGE_BS_DEGEN            33028
#define ID_OP_PURGE_BS_PROM             33031
#define ID_OP_ELEV_TRANSFORM            33033
#define ID_EDIT_TRANSFER                33035
#define ID_OP_DIAG_SWI                  33037
#define ID_EDIT_SWI                     33038
#define ID_OP_DLPR_FILL                 33049
#define ID_OP_PURGE_BS_REDUN            33050
#define ID_IMPRESS                      33051
#define ID_OP_TREE_TRANSFORM            33053
#define ID_FILE_CSV                     33054
#define ID_GRAPH_SELECT                 33058
#define ID_OP_DIAG_AMBOFF               33060
#define ID_OP_DIAG_OVLP_NBRS            33061
#define ID_EDIT_PASTE_DATABASE          33062
#define ID_EDIT_COPY_DATABASE           33063
#define ID_OPEN_DATABASE                33064
#define ID_MERGE_DATABASE               33065
#define ID_SAVE_DATABASE                33066
#define ID_SAVEAS_DATABASE              33067
#define ID_INFO_DATABASE                33068
#define ID_CLOSE_DATABASE               33069
#define ID_VIEW_TB_DATABASE             33072
#define ID_LIST_DATABASE                33073
#define ID_EDIT_RECORD                  33074
#define ID_OP_DLPR_CONSOL               33085
#define ID_OP_DATA_ALIGN                33088
#define ID_VIEW_MAP_RELIEF              33090
#define ID_EDIT_BROWSE                  33106
#define ID_FEATURE_BROWSE               33109
#define ID_OP_DLPR_CHECK                33116
#define ID_OP_ELEV_CROP                 33117
#define ID_OP_DLPR_CROP                 33118
#define ID_RECORD_CENTER                33119
#define ID_RECORD_BROWSE                33120
#define ID_RECORD_UNLIST                33121
#define ID_RECORD_EDIT                  33122
#define ID_RECORD_DELETE                33123
#define ID_GP_BROWSE                    33124
#define ID_OP_PURGE_BS_DRG              33125
#define ID_OP_ANALYZE_BASINS            33126
#define ID_GP_RQF                       33131
#define ID_RECORD_RQF                   33133
#define ID_FEATURE_RQF                  33134
#define ID_EDIT_RQF                     33135
#define ID_OP_ERROR_ANAL                33136
#define ID_LIST_APPEND                  33138
#define ID_LIST_LOAD                    33139
#define ID_LIST_SAVE                    33140
#define ID_VIEW_LABEL_STATUS            33141
#define ID_LIST_EDITED                  33142
#define ID_OP_TREE_SHORELINE            33143
#define ID_HELP_QUICK                   33144
#define ID_OP_TREE_DATA                 33145
#define ID_OP_PURGE_NOISE               33147
#define ID_GP_MARK_POINT                33148
#define ID_OP_REVERT                    33152
#define ID_OP_RESORT_ALL                33154
#define ID_OP_RESORT_PEAKS              33157
#define ID_OP_RESORT_BS                 33158
#define ID_OP_DATA_PURGE                33159
#define ID_VIEW_FACTORY                 33160
#define ID_VIEW_RELOAD                  33161
#define ID_VIEW_SAVE                    33162
#define ID_VIEW_AUTOSAVE                33163
#define ID_VIEW_SET                     33165
#define ID_OPEN_MARK_MAP                33167
#define ID_SAVEAS_MARK_MAP              33168
#define ID_VIEW_RIDGE_OPTIONS           33169
#define ID_VIEW_MAP_DOMAINS             33170
#define ID_VIEW_MAP_GRID                33171
#define ID_VIEW_APPLY                   33172
#define ID_VIEW_FEATURES_OPTIONS        33174
#define ID_VIEW_MAP_CUTOFFS             33175
#define ID_OP_DOMAP_PURGE               33176
#define ID_ZERO_PROB                    33177
#define ID_LIST_PARENTS                 33178
#define ID_EDIT_MOVEUP                  33180
#define ID_EDIT_MOVEDOWN                33181
#define ID_FEATURE_LIST_PARENTS         33182
#define ID_OP_SS_PROM                   33183
#define ID_OP_SS_UNKNOWN                33184
#define ID_GP_NEW_PEAK                  33187
#define ID_GP_NEW_SADDLE                33188
#define ID_OP_SS_REAL                   33190
#define ID_SADDLE_STAT                  33191
#define ID_VIEW_UPDATE_AUTO             33193
#define ID_VIEW_UPDATE_NOW              33194
#define ID_VIEW_BROWSER                 33195
#define ID_VIEW_BROWSER_REUSE           33196
#define ID_VIEW_BROWSER_VIEW            33197
#define ID_VIEW_BROWSER_URL             33198
#define ID_VIEW_BROWSER_RELOAD          33199
#define ID_VIEW_ZOOM_SCALE              33200
#define ID_IDENTIFY_PARENT_LINE         33201
#define ID_IDENTIFY_PARENT_CELL         33202
#define ID_IDENTIFY_NBR_1               33204
#define ID_IDENTIFY_NBR_2               33205
#define ID_IDENTIFY_NBR_BOTH            33206
#define ID_IDENTIFY_PARENT_ISLAND       33207
#define ID_FREE_HEIGHT                  33208
#define ID_INDICATOR_LOC                60000
#define ID_INDICATOR_ELEV               60001
#define ID_INDICATOR_HEIGHT             60002
#define ID_INDICATOR_WIDTH              60003
#define ID_INDICATOR_NITEM              60004
#define ID_INDICATOR_NSELECT            60005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        291
#define _APS_NEXT_COMMAND_VALUE         33209
#define _APS_NEXT_CONTROL_VALUE         1701
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
